# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  http:
    port: 9093
    targetPort: 9093
  ui:
    port: 80
    targetPort: 80

namespace: dev-samples
imagePullSecrets:
  - name: regcred

ingress:
  enabled: true
  className: nginx-internal
  annotations:
    http:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt
    ui:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt
  domainPrefixHttp: oasf-agent-financial-assist
  domainPrefixUi: oasf-ui-financial-assist
  apiDomainName: dev.example.com

serviceAccount:
  create: true
  name: ""

externalSecrets:
  secretStoreName: ""
  secretStoreKind: ClusterSecretStore
  data:
    - secretKey: IDENTITY_PLATFORM_API_KEY
      remoteRef:
        key: ""
        property: IDENTITY_PLATFORM_API_KEY
    - secretKey: AZURE_OPENAI_API_KEY
      remoteRef:
        key: ""
        property: AZURE_OPENAI_API_KEY
    - secretKey: AZURE_OPENAI_ENDPOINT
      remoteRef:
        key: ""
        property: AZURE_OPENAI_ENDPOINT


configmap:
  CURRENCY_EXCHANGE_AGENT_URL: ""
  CURRENCY_EXCHANGE_MCP_SERVER_URL: ""
  IDENTITY_PLATFORM_GRPC_SERVER_URL: "api.grpc.identity-platform.staging.outshift.ai"
  PORT: "9093"
  LOG_LEVEL: "INFO"
