# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agntcy/identity/platform/v1alpha1/app.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+agntcy/identity/platform/v1alpha1/app.proto\x12!agntcy.identity.platform.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n\x03\x41pp\x12\x13\n\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x02R\x0b\x64\x65scription\x88\x01\x01\x12\x43\n\x04type\x18\x04 \x01(\x0e\x32*.agntcy.identity.platform.v1alpha1.AppTypeH\x03R\x04type\x88\x01\x01\x12\x1c\n\x07\x61pi_key\x18\x05 \x01(\tH\x04R\x06\x61piKey\x88\x01\x01\x12>\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x05R\tcreatedAt\x88\x01\x01\x12>\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x06R\tupdatedAt\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_nameB\x0e\n\x0c_descriptionB\x07\n\x05_typeB\n\n\x08_api_keyB\r\n\x0b_created_atB\r\n\x0b_updated_at*m\n\x07\x41ppType\x12\x18\n\x14\x41PP_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41PP_TYPE_AGENT_A2A\x10\x01\x12\x17\n\x13\x41PP_TYPE_AGENT_OASF\x10\x02\x12\x17\n\x13\x41PP_TYPE_MCP_SERVER\x10\x03\x42\xc3\x02\n%com.agntcy.identity.platform.v1alpha1B\x08\x41ppProtoP\x01Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\xa2\x02\x03\x41IP\xaa\x02!Agntcy.Identity.Platform.V1alpha1\xca\x02!Agntcy\\Identity\\Platform\\V1alpha1\xe2\x02-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\xea\x02$Agntcy::Identity::Platform::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agntcy.identity.platform.v1alpha1.app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.agntcy.identity.platform.v1alpha1B\010AppProtoP\001Zigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_go\242\002\003AIP\252\002!Agntcy.Identity.Platform.V1alpha1\312\002!Agntcy\\Identity\\Platform\\V1alpha1\342\002-Agntcy\\Identity\\Platform\\V1alpha1\\GPBMetadata\352\002$Agntcy::Identity::Platform::V1alpha1'
  _globals['_APPTYPE']._serialized_start=518
  _globals['_APPTYPE']._serialized_end=627
  _globals['_APP']._serialized_start=116
  _globals['_APP']._serialized_end=516
# @@protoc_insertion_point(module_scope)
