FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c AS builder

WORKDIR /src
COPY ./backend ./identity
WORKDIR /src/identity
RUN cd ./cmd/bff && go mod download
