FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c AS builder

# Build the package
WORKDIR /build
COPY ./backend .
RUN cd ./cmd/bff && go build -o ../../identity-bff

RUN apk upgrade --no-cache openssl && \
    apk add --no-cache ca-certificates wget && \
    update-ca-certificates

FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c

RUN apk upgrade --no-cache openssl

# Create a group and user
RUN addgroup -S web && adduser -u 1999 -S -G web web

# Set workdir
WORKDIR /home/web

COPY --from=builder /build/identity-bff .

# Give permissions
RUN chmod +x identity-bff && \
    chown -R web:web .

USER web

ENTRYPOINT ["./identity-bff"]
