# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

FROM node:22-alpine AS build

# set NPM_TOKEN as an ENV var
ARG NPM_TOKEN

ENV NPM_TOKEN=${NPM_TOKEN}

# Install packages
RUN apk add --update \
  libpng-dev \
  build-base \
  nodejs \
  npm \
  yarn

# Set workdir
WORKDIR /home/web

# Copy src
COPY ./frontend .

RUN touch .env && echo "NPM_TOKEN=${NPM_TOKEN}" >> .env

# Install libs
RUN yarn install
