# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

compressionLevel: mixed

enableGlobalCache: false

injectEnvironmentFiles:
  - .env

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
