// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ThalesIdpSettings Thales IdP Settings
//
// swagger:model v1alpha1ThalesIdpSettings
type V1alpha1ThalesIdpSettings struct {

	// issuer Url
	IssuerURL string `json:"issuerUrl,omitempty"`

	// registration Url
	RegistrationURL string `json:"registrationUrl,omitempty"`

	// secret Id
	SecretID string `json:"secretId,omitempty"`

	// secret key value
	SecretKeyValue string `json:"secretKeyValue,omitempty"`
}

// Validate validates this v1alpha1 thales idp settings
func (m *V1alpha1ThalesIdpSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 thales idp settings based on context it is used
func (m *V1alpha1ThalesIdpSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ThalesIdpSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ThalesIdpSettings) UnmarshalBinary(b []byte) error {
	var res V1alpha1ThalesIdpSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
