// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1PagedResponse Pagination response
//
// swagger:model v1alpha1PagedResponse
type V1alpha1PagedResponse struct {

	// Has next page
	HasNextPage bool `json:"hasNextPage,omitempty"`

	// Next page
	NextPage int32 `json:"nextPage,omitempty"`

	// The size of the current page
	Size int32 `json:"size,omitempty"`

	// The total size of items
	Total string `json:"total,omitempty"`
}

// Validate validates this v1alpha1 paged response
func (m *V1alpha1PagedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 paged response based on context it is used
func (m *V1alpha1PagedResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1PagedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1PagedResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1PagedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
