// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1OktaIdpSettings Okta IdP Settings
//
// swagger:model v1alpha1OktaIdpSettings
type V1alpha1OktaIdpSettings struct {

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// org Url
	OrgURL string `json:"orgUrl,omitempty"`

	// private key
	PrivateKey string `json:"privateKey,omitempty"`
}

// Validate validates this v1alpha1 okta idp settings
func (m *V1alpha1OktaIdpSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 okta idp settings based on context it is used
func (m *V1alpha1OktaIdpSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1OktaIdpSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1OktaIdpSettings) UnmarshalBinary(b []byte) error {
	var res V1alpha1OktaIdpSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
