// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1GetPoliciesCountResponse v1alpha1 get policies count response
//
// swagger:model v1alpha1GetPoliciesCountResponse
type V1alpha1GetPoliciesCountResponse struct {

	// The total count
	Total string `json:"total,omitempty"`
}

// Validate validates this v1alpha1 get policies count response
func (m *V1alpha1GetPoliciesCountResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 get policies count response based on context it is used
func (m *V1alpha1GetPoliciesCountResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1GetPoliciesCountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1GetPoliciesCountResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1GetPoliciesCountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
