// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1CreateOasfAppResponse v1alpha1 create oasf app response
//
// swagger:model v1alpha1CreateOasfAppResponse
type V1alpha1CreateOasfAppResponse struct {

	// The created OASF App.
	App *V1alpha1App `json:"app,omitempty"`

	// The issued badge for the OASF App.
	Badge *V1alpha1Badge `json:"badge,omitempty"`
}

// Validate validates this v1alpha1 create oasf app response
func (m *V1alpha1CreateOasfAppResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBadge(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1CreateOasfAppResponse) validateApp(formats strfmt.Registry) error {
	if swag.IsZero(m.App) { // not required
		return nil
	}

	if m.App != nil {
		if err := m.App.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app")
			}

			return err
		}
	}

	return nil
}

func (m *V1alpha1CreateOasfAppResponse) validateBadge(formats strfmt.Registry) error {
	if swag.IsZero(m.Badge) { // not required
		return nil
	}

	if m.Badge != nil {
		if err := m.Badge.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("badge")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("badge")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 create oasf app response based on the context it is used
func (m *V1alpha1CreateOasfAppResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApp(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBadge(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1CreateOasfAppResponse) contextValidateApp(ctx context.Context, formats strfmt.Registry) error {

	if m.App != nil {

		if swag.IsZero(m.App) { // not required
			return nil
		}

		if err := m.App.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app")
			}

			return err
		}
	}

	return nil
}

func (m *V1alpha1CreateOasfAppResponse) contextValidateBadge(ctx context.Context, formats strfmt.Registry) error {

	if m.Badge != nil {

		if swag.IsZero(m.Badge) { // not required
			return nil
		}

		if err := m.Badge.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("badge")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("badge")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1CreateOasfAppResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1CreateOasfAppResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1CreateOasfAppResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
