// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1CreateOasfAppRequest v1alpha1 create oasf app request
//
// swagger:model v1alpha1CreateOasfAppRequest
type V1alpha1CreateOasfAppRequest struct {

	// The OASF schema in a base64 encoded format
	SchemaBase64 string `json:"schemaBase64,omitempty"`
}

// Validate validates this v1alpha1 create oasf app request
func (m *V1alpha1CreateOasfAppRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 create oasf app request based on context it is used
func (m *V1alpha1CreateOasfAppRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1CreateOasfAppRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1CreateOasfAppRequest) UnmarshalBinary(b []byte) error {
	var res V1alpha1CreateOasfAppRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
