// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1BadgeClaims BadgeClaims represents the content of a Badge VC defined [here]
//
// swagger:model v1alpha1BadgeClaims
//
// [here]: https://spec.identity.agntcy.org/docs/vc/intro/
type V1alpha1BadgeClaims struct {

	// The content of the badge
	Badge string `json:"badge,omitempty"`

	// The ID as defined [here]
	//
	// [here]: https://www.w3.org/TR/vc-data-model/#credential-subject
	ID string `json:"id,omitempty"`
}

// Validate validates this v1alpha1 badge claims
func (m *V1alpha1BadgeClaims) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 badge claims based on context it is used
func (m *V1alpha1BadgeClaims) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1BadgeClaims) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1BadgeClaims) UnmarshalBinary(b []byte) error {
	var res V1alpha1BadgeClaims
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
