// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ErrorInfo v1alpha1 error info
//
// swagger:model v1alpha1ErrorInfo
type V1alpha1ErrorInfo struct {

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`
}

// Validate validates this v1alpha1 error info
func (m *V1alpha1ErrorInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 error info based on context it is used
func (m *V1alpha1ErrorInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ErrorInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ErrorInfo) UnmarshalBinary(b []byte) error {
	var res V1alpha1ErrorInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
