// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1KeycloakIdpSettings Keycloak IdP Settings
//
// swagger:model v1alpha1KeycloakIdpSettings
type V1alpha1KeycloakIdpSettings struct {

	// base Url
	BaseURL string `json:"baseUrl,omitempty"`

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// client secret
	ClientSecret string `json:"clientSecret,omitempty"`

	// realm
	Realm string `json:"realm,omitempty"`
}

// Validate validates this v1alpha1 keycloak idp settings
func (m *V1alpha1KeycloakIdpSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 keycloak idp settings based on context it is used
func (m *V1alpha1KeycloakIdpSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1KeycloakIdpSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1KeycloakIdpSettings) UnmarshalBinary(b []byte) error {
	var res V1alpha1KeycloakIdpSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
