---
all: false
dir: "{{.InterfaceDir}}/mocks"
with-expecter: true
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"
packages:
  github.com/outshift/identity-service/internal/core/auth:
    interfaces:
      Repository:
  github.com/outshift/identity-service/internal/core/app:
    interfaces:
      Repository:
  github.com/outshift/identity-service/internal/core/badge:
    interfaces:
      Repository:
  github.com/outshift/identity-service/internal/core/device:
    interfaces:
      Repository:
  github.com/outshift/identity-service/internal/core/policy:
    interfaces:
      Repository:
      Evaluator:
  github.com/outshift/identity-service/internal/core/settings:
    interfaces:
      Repository: