---
all: false
dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
filename: "{{.InterfaceName | snakecase}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/agntcy/identity-service/internal/core/app:
    interfaces:
      Repository: {}
  github.com/agntcy/identity-service/internal/core/auth:
    interfaces:
      Repository: {}
  github.com/agntcy/identity-service/internal/core/badge:
    interfaces:
      Repository: {}
      Revoker: {}
  github.com/agntcy/identity-service/internal/core/badge/a2a:
    interfaces:
      DiscoveryClient: {}
  github.com/agntcy/identity-service/internal/core/badge/mcp:
    interfaces:
      DiscoveryClient: {}
  github.com/agntcy/identity-service/internal/core/device:
    interfaces:
      Repository: {}
  github.com/agntcy/identity-service/internal/core/policy:
    interfaces:
      Evaluator: {}
      PolicyRepository: {}
      RuleRepository: {}
      TaskRepository: {}
      TaskService: {}
  github.com/agntcy/identity-service/internal/core/settings:
    interfaces:
      Repository: {}
      IssuerService: {}
  github.com/agntcy/identity-service/internal/core/idp:
    interfaces:
      CredentialStore: {}
  github.com/agntcy/identity-service/internal/core/identity:
    interfaces:
      KeyStore: {}
      Service: {}
  github.com/agntcy/identity-service/internal/bff:
    interfaces:
      AppService: {}
      AuthService: {}
      BadgeService: {}
      DeviceService: {}
      NotificationService: {}
      PolicyService: {}
      SettingsService: {}
  github.com/agntcy/identity-service/internal/core/iam:
    interfaces:
      Repository: {}
  github.com/agntcy/identity-service/internal/pkg/iam:
    interfaces:
      Client: {}
      JwtVerifier: {}
  github.com/agntcy/identity-service/internal/pkg/vault:
    interfaces:
      VaultClient: {}
  github.com/agntcy/identity-service/internal/pkg/webpush:
    interfaces:
      WebPushSender: {}
