"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
"""

from agntcy.identity.service.v1alpha1 import badge_pb2 as _badge_pb2
from agntcy.identity.service.v1alpha1 import badge_service_pb2 as _badge_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BadgeServiceStub:
    """BadgeService manages badges."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BadgeServiceAsyncStub: ...
    IssueBadge: _grpc.UnaryUnaryMultiCallable[_badge_service_pb2.IssueBadgeRequest, _badge_pb2.Badge]
    """Create a new Badge."""
    VerifyBadge: _grpc.UnaryUnaryMultiCallable[_badge_service_pb2.VerifyBadgeRequest, _badge_pb2.VerificationResult]
    """Verify a badge."""

@_typing.type_check_only
class BadgeServiceAsyncStub(BadgeServiceStub):
    """BadgeService manages badges."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    IssueBadge: _aio.UnaryUnaryMultiCallable[_badge_service_pb2.IssueBadgeRequest, _badge_pb2.Badge]  # type: ignore[assignment]
    """Create a new Badge."""
    VerifyBadge: _aio.UnaryUnaryMultiCallable[_badge_service_pb2.VerifyBadgeRequest, _badge_pb2.VerificationResult]  # type: ignore[assignment]
    """Verify a badge."""

class BadgeServiceServicer(metaclass=_abc_1.ABCMeta):
    """BadgeService manages badges."""

    @_abc_1.abstractmethod
    def IssueBadge(
        self,
        request: _badge_service_pb2.IssueBadgeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_badge_pb2.Badge, _abc.Awaitable[_badge_pb2.Badge]]:
        """Create a new Badge."""

    @_abc_1.abstractmethod
    def VerifyBadge(
        self,
        request: _badge_service_pb2.VerifyBadgeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_badge_pb2.VerificationResult, _abc.Awaitable[_badge_pb2.VerificationResult]]:
        """Verify a badge."""

def add_BadgeServiceServicer_to_server(servicer: BadgeServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
