"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
"""

from agntcy.identity.service.v1alpha1 import device_pb2 as _device_pb2
from agntcy.identity.service.v1alpha1 import device_service_pb2 as _device_service_pb2
from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DeviceServiceStub:
    """DeviceService manages device."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DeviceServiceAsyncStub: ...
    AddDevice: _grpc.UnaryUnaryMultiCallable[_device_service_pb2.AddDeviceRequest, _device_pb2.Device]
    """Add new device for approval flow"""
    RegisterDevice: _grpc.UnaryUnaryMultiCallable[_device_service_pb2.RegisterDeviceRequest, _empty_pb2.Empty]
    """Add new device for approval flow"""
    ListDevices: _grpc.UnaryUnaryMultiCallable[_device_service_pb2.ListDevicesRequest, _device_service_pb2.ListDevicesResponse]
    """List all registered devices"""
    DeleteDevice: _grpc.UnaryUnaryMultiCallable[_device_service_pb2.DeleteDeviceRequest, _empty_pb2.Empty]
    """Delete a registered Device."""
    TestDevice: _grpc.UnaryUnaryMultiCallable[_device_service_pb2.TestDeviceRequest, _empty_pb2.Empty]
    """Send a test notification to a registered device to see if it's well configured."""

@_typing.type_check_only
class DeviceServiceAsyncStub(DeviceServiceStub):
    """DeviceService manages device."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    AddDevice: _aio.UnaryUnaryMultiCallable[_device_service_pb2.AddDeviceRequest, _device_pb2.Device]  # type: ignore[assignment]
    """Add new device for approval flow"""
    RegisterDevice: _aio.UnaryUnaryMultiCallable[_device_service_pb2.RegisterDeviceRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Add new device for approval flow"""
    ListDevices: _aio.UnaryUnaryMultiCallable[_device_service_pb2.ListDevicesRequest, _device_service_pb2.ListDevicesResponse]  # type: ignore[assignment]
    """List all registered devices"""
    DeleteDevice: _aio.UnaryUnaryMultiCallable[_device_service_pb2.DeleteDeviceRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Delete a registered Device."""
    TestDevice: _aio.UnaryUnaryMultiCallable[_device_service_pb2.TestDeviceRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Send a test notification to a registered device to see if it's well configured."""

class DeviceServiceServicer(metaclass=_abc_1.ABCMeta):
    """DeviceService manages device."""

    @_abc_1.abstractmethod
    def AddDevice(
        self,
        request: _device_service_pb2.AddDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_device_pb2.Device, _abc.Awaitable[_device_pb2.Device]]:
        """Add new device for approval flow"""

    @_abc_1.abstractmethod
    def RegisterDevice(
        self,
        request: _device_service_pb2.RegisterDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Add new device for approval flow"""

    @_abc_1.abstractmethod
    def ListDevices(
        self,
        request: _device_service_pb2.ListDevicesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_device_service_pb2.ListDevicesResponse, _abc.Awaitable[_device_service_pb2.ListDevicesResponse]]:
        """List all registered devices"""

    @_abc_1.abstractmethod
    def DeleteDevice(
        self,
        request: _device_service_pb2.DeleteDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Delete a registered Device."""

    @_abc_1.abstractmethod
    def TestDevice(
        self,
        request: _device_service_pb2.TestDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Send a test notification to a registered device to see if it's well configured."""

def add_DeviceServiceServicer_to_server(servicer: DeviceServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
