# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

version: v1
managed:
  enabled: true
plugins:
  - name: openapi
    out: .
    opt:
      - default_response=true
      - enum_type=string
