# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "agntcy-identity-service-sdk"
version = "0.0.8"
authors = [
    {name = "Jean Diaconu", email = "jdiaconu@cisco.com"},
]
description = "AGNTCY Identity Service SDK & CLI for Python"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = ["grpcio", "grpcio-status", "googleapis-common-protos", "protobuf", "grpcio-tools", "protoc_gen_openapiv2", "python-dotenv", "mcp (<2.0.0)", "typer", "httpx", "starlette", "a2a-sdk (>=0.2.0)", "types-protobuf", "types-grpcio", "types-grpcio-status"]

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio"]
lint = ["pylint", "ruff", "mypy"]

[project.urls]
"Homepage" = "https://github.com/agntcy/identity-service/sdk/python"
"Bug Tracker" = "https://github.com/agntcy/identity-service/issues"

[project.scripts]
identity-cli = "identityservice.cli:app"

[tool.setuptools]
packages = ["identityservice", "identityservice.commands", "identityservice.auth", "identityservice.badge", "openapiv3", "google.api", "agntcy.identity.service.v1alpha1"]

[tool.pytest.ini_options]
minversion = "8.0.0"
testpaths = [
  "tests",
]

[tool.ruff]
line-length = 80
extend-include = [
  "*.ipynb"
]
exclude = [
  ".ipynb_checkpoints",
  "agntcy",
  "google",
  "openapiv3"
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104", "F401", "F403"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pylint]
prefer-stubs = true
ignore-paths = ".venv,agntcy,google,build,openapiv3,protoc_gen_openapiv2"

[tool.mypy]
exclude = "^(protoc_gen_openapiv2)"

[[tool.mypy.overrides]]
module = ["google.*", "protoc_gen_openapiv2.*"]
ignore_errors = true
