# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: identity-postgres
services:
  identity-postgres:
    image: postgres:latest
    container_name: identity-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432"
    env_file:
      - .env
