# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: identity-node
include:
  - docker-compose.db.yml
services:
  identity-node:
    container_name: identity-node
    image: ghcr.io/agntcy/identity/node:latest
    restart: always
    depends_on:
      - identity-postgres
    ports:
      - "4003:4000"
      - "4004:4001"
    env_file:
      - .env
