# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: identity-service-backend
description: A Helm chart for identity-service backend
type: application
version: 0.1.8
appVersion: "0.0.1"

maintainers:
  - name: identity
    url: https://github.com/agntcy/identity-service/blob/main/MAINTAINERS.md
sources:
  - https://github.com/agntcy/identity-service

dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: vault
    version: 0.23.0
    repository: https://helm.releases.hashicorp.com
