// Copyright 2025 Cisco Systems, Inc. and its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: outshift/identity/service/v1alpha1/auth_service.proto

package identity_service_sdk_go

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The App information.
	App           *App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfoResponse) Reset() {
	*x = AppInfoResponse{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfoResponse) ProtoMessage() {}

func (x *AppInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfoResponse.ProtoReflect.Descriptor instead.
func (*AppInfoResponse) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppInfoResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolver metadata id for which authorization is requested.
	ResolverMetadataId *string `protobuf:"bytes,1,opt,name=resolver_metadata_id,json=resolverMetadataId,proto3,oneof" json:"resolver_metadata_id,omitempty"`
	// The MCP Server tool name.
	ToolName *string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3,oneof" json:"tool_name,omitempty"`
	// The User context in the form of an id or access token.
	// Mandatory for User Approval Flows.
	UserToken     *string `protobuf:"bytes,3,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeRequest) GetResolverMetadataId() string {
	if x != nil && x.ResolverMetadataId != nil {
		return *x.ResolverMetadataId
	}
	return ""
}

func (x *AuthorizeRequest) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

func (x *AuthorizeRequest) GetUserToken() string {
	if x != nil && x.UserToken != nil {
		return *x.UserToken
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If authorization is successful, return a code to be used for
	// the token endpoint.
	AuthorizationCode string `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

type TokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pass the code received from the authorization endpoint.
	AuthorizationCode string `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token issued to the Agent or MCP Server.
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ExtAuthzRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The access token to be authorized.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The tool name that will be invoked
	ToolName      *string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3,oneof" json:"tool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtAuthzRequest) Reset() {
	*x = ExtAuthzRequest{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtAuthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtAuthzRequest) ProtoMessage() {}

func (x *ExtAuthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtAuthzRequest.ProtoReflect.Descriptor instead.
func (*ExtAuthzRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExtAuthzRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExtAuthzRequest) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

type ApproveTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The device id used to handle the approval requestion
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// The session id related to the token that needs to be approved
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The OTP sent to the device related to the request
	Otp string `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	// The action made by the user (true: allow the token, false: deny the token)
	Approve       bool `protobuf:"varint,4,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTokenRequest) Reset() {
	*x = ApproveTokenRequest{}
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTokenRequest) ProtoMessage() {}

func (x *ApproveTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTokenRequest.ProtoReflect.Descriptor instead.
func (*ApproveTokenRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApproveTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApproveTokenRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *ApproveTokenRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

var File_outshift_identity_service_v1alpha1_auth_service_proto protoreflect.FileDescriptor

const file_outshift_identity_service_v1alpha1_auth_service_proto_rawDesc = "" +
	"\n" +
	"5outshift/identity/service/v1alpha1/auth_service.proto\x12\"outshift.identity.service.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a,outshift/identity/service/v1alpha1/app.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"L\n" +
	"\x0fAppInfoResponse\x129\n" +
	"\x03app\x18\x01 \x01(\v2'.outshift.identity.service.v1alpha1.AppR\x03app\"\xc5\x01\n" +
	"\x10AuthorizeRequest\x125\n" +
	"\x14resolver_metadata_id\x18\x01 \x01(\tH\x00R\x12resolverMetadataId\x88\x01\x01\x12 \n" +
	"\ttool_name\x18\x02 \x01(\tH\x01R\btoolName\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_token\x18\x03 \x01(\tH\x02R\tuserToken\x88\x01\x01B\x17\n" +
	"\x15_resolver_metadata_idB\f\n" +
	"\n" +
	"_tool_nameB\r\n" +
	"\v_user_token\"B\n" +
	"\x11AuthorizeResponse\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\"=\n" +
	"\fTokenRequest\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\"2\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"d\n" +
	"\x0fExtAuthzRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12 \n" +
	"\ttool_name\x18\x02 \x01(\tH\x00R\btoolName\x88\x01\x01B\f\n" +
	"\n" +
	"_tool_name\"}\n" +
	"\x13ApproveTokenRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otp\x12\x18\n" +
	"\aapprove\x18\x04 \x01(\bR\aapprove2\xe0\a\n" +
	"\vAuthService\x12\x91\x01\n" +
	"\aAppInfo\x12\x16.google.protobuf.Empty\x1a3.outshift.identity.service.v1alpha1.AppInfoResponse\"9\x92A\x17\x12\fGet App Info*\aAppInfo\x82\xd3\xe4\x93\x02\x19\x12\x17/v1alpha1/auth/app_info\x12\xdc\x01\n" +
	"\tAuthorize\x124.outshift.identity.service.v1alpha1.AuthorizeRequest\x1a5.outshift.identity.service.v1alpha1.AuthorizeResponse\"b\x92A<\x12/Authorize a request from an Agent or MCP Server*\tAuthorize\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1alpha1/auth/authorize\x12\xc8\x01\n" +
	"\x05Token\x120.outshift.identity.service.v1alpha1.TokenRequest\x1a1.outshift.identity.service.v1alpha1.TokenResponse\"Z\x92A8\x12(Request token for an Agent or MCP Server*\fRequestToken\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1alpha1/auth/token\x12\xb1\x01\n" +
	"\bExtAuthz\x123.outshift.identity.service.v1alpha1.ExtAuthzRequest\x1a\x16.google.protobuf.Empty\"X\x92A2\x12&Handle external authorization requests*\bExtAuthz\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1alpha1/auth/ext_authz\x12\xd3\x01\n" +
	"\fApproveToken\x127.outshift.identity.service.v1alpha1.ApproveTokenRequest\x1a\x16.google.protobuf.Empty\"r\x92AH\x128Handle manual approval of external authorization requets*\fApproveToken\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1alpha1/auth/approve_token\x1a\t\x92A\x06\n" +
	"\x04AuthBlZjgithub.com/outshift/identity-service/api/server/outshift/identity/service/v1alpha1;identity_service_sdk_gob\x06proto3"

var (
	file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescOnce sync.Once
	file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescData []byte
)

func file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescGZIP() []byte {
	file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescOnce.Do(func() {
		file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_auth_service_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_auth_service_proto_rawDesc)))
	})
	return file_outshift_identity_service_v1alpha1_auth_service_proto_rawDescData
}

var file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_outshift_identity_service_v1alpha1_auth_service_proto_goTypes = []any{
	(*AppInfoResponse)(nil),     // 0: outshift.identity.service.v1alpha1.AppInfoResponse
	(*AuthorizeRequest)(nil),    // 1: outshift.identity.service.v1alpha1.AuthorizeRequest
	(*AuthorizeResponse)(nil),   // 2: outshift.identity.service.v1alpha1.AuthorizeResponse
	(*TokenRequest)(nil),        // 3: outshift.identity.service.v1alpha1.TokenRequest
	(*TokenResponse)(nil),       // 4: outshift.identity.service.v1alpha1.TokenResponse
	(*ExtAuthzRequest)(nil),     // 5: outshift.identity.service.v1alpha1.ExtAuthzRequest
	(*ApproveTokenRequest)(nil), // 6: outshift.identity.service.v1alpha1.ApproveTokenRequest
	(*App)(nil),                 // 7: outshift.identity.service.v1alpha1.App
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_outshift_identity_service_v1alpha1_auth_service_proto_depIdxs = []int32{
	7, // 0: outshift.identity.service.v1alpha1.AppInfoResponse.app:type_name -> outshift.identity.service.v1alpha1.App
	8, // 1: outshift.identity.service.v1alpha1.AuthService.AppInfo:input_type -> google.protobuf.Empty
	1, // 2: outshift.identity.service.v1alpha1.AuthService.Authorize:input_type -> outshift.identity.service.v1alpha1.AuthorizeRequest
	3, // 3: outshift.identity.service.v1alpha1.AuthService.Token:input_type -> outshift.identity.service.v1alpha1.TokenRequest
	5, // 4: outshift.identity.service.v1alpha1.AuthService.ExtAuthz:input_type -> outshift.identity.service.v1alpha1.ExtAuthzRequest
	6, // 5: outshift.identity.service.v1alpha1.AuthService.ApproveToken:input_type -> outshift.identity.service.v1alpha1.ApproveTokenRequest
	0, // 6: outshift.identity.service.v1alpha1.AuthService.AppInfo:output_type -> outshift.identity.service.v1alpha1.AppInfoResponse
	2, // 7: outshift.identity.service.v1alpha1.AuthService.Authorize:output_type -> outshift.identity.service.v1alpha1.AuthorizeResponse
	4, // 8: outshift.identity.service.v1alpha1.AuthService.Token:output_type -> outshift.identity.service.v1alpha1.TokenResponse
	8, // 9: outshift.identity.service.v1alpha1.AuthService.ExtAuthz:output_type -> google.protobuf.Empty
	8, // 10: outshift.identity.service.v1alpha1.AuthService.ApproveToken:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_outshift_identity_service_v1alpha1_auth_service_proto_init() }
func file_outshift_identity_service_v1alpha1_auth_service_proto_init() {
	if File_outshift_identity_service_v1alpha1_auth_service_proto != nil {
		return
	}
	file_outshift_identity_service_v1alpha1_app_proto_init()
	file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_auth_service_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outshift_identity_service_v1alpha1_auth_service_proto_goTypes,
		DependencyIndexes: file_outshift_identity_service_v1alpha1_auth_service_proto_depIdxs,
		MessageInfos:      file_outshift_identity_service_v1alpha1_auth_service_proto_msgTypes,
	}.Build()
	File_outshift_identity_service_v1alpha1_auth_service_proto = out.File
	file_outshift_identity_service_v1alpha1_auth_service_proto_goTypes = nil
	file_outshift_identity_service_v1alpha1_auth_service_proto_depIdxs = nil
}
