// Copyright 2025 Cisco Systems, Inc. and its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: outshift/identity/service/v1alpha1/badge_service.proto

package identity_service_sdk_go

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueBadgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App Id.
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// The A2A badge.
	A2A *IssueA2ABadgeRequest `protobuf:"bytes,2,opt,name=a2a,proto3" json:"a2a,omitempty"`
	// The MCP badge.
	Mcp *IssueMcpBadgeRequest `protobuf:"bytes,3,opt,name=mcp,proto3" json:"mcp,omitempty"`
	// The OASF badge.
	Oasf          *IssueOASFBadgeRequest `protobuf:"bytes,4,opt,name=oasf,proto3" json:"oasf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueBadgeRequest) Reset() {
	*x = IssueBadgeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueBadgeRequest) ProtoMessage() {}

func (x *IssueBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueBadgeRequest.ProtoReflect.Descriptor instead.
func (*IssueBadgeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP(), []int{0}
}

func (x *IssueBadgeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *IssueBadgeRequest) GetA2A() *IssueA2ABadgeRequest {
	if x != nil {
		return x.A2A
	}
	return nil
}

func (x *IssueBadgeRequest) GetMcp() *IssueMcpBadgeRequest {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *IssueBadgeRequest) GetOasf() *IssueOASFBadgeRequest {
	if x != nil {
		return x.Oasf
	}
	return nil
}

type IssueMcpBadgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MCP badge name.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The MCP badge URL.
	Url *string `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	// Or the MCP Schema in a base64 encoded format.
	SchemaBase64  *string `protobuf:"bytes,3,opt,name=schema_base64,json=schemaBase64,proto3,oneof" json:"schema_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMcpBadgeRequest) Reset() {
	*x = IssueMcpBadgeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMcpBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMcpBadgeRequest) ProtoMessage() {}

func (x *IssueMcpBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMcpBadgeRequest.ProtoReflect.Descriptor instead.
func (*IssueMcpBadgeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP(), []int{1}
}

func (x *IssueMcpBadgeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *IssueMcpBadgeRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *IssueMcpBadgeRequest) GetSchemaBase64() string {
	if x != nil && x.SchemaBase64 != nil {
		return *x.SchemaBase64
	}
	return ""
}

type IssueA2ABadgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The A2A well_known_url.
	WellKnownUrl *string `protobuf:"bytes,1,opt,name=well_known_url,json=wellKnownUrl,proto3,oneof" json:"well_known_url,omitempty"`
	// Or the MCP Schema in a base64 encoded format.
	SchemaBase64  *string `protobuf:"bytes,2,opt,name=schema_base64,json=schemaBase64,proto3,oneof" json:"schema_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueA2ABadgeRequest) Reset() {
	*x = IssueA2ABadgeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueA2ABadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueA2ABadgeRequest) ProtoMessage() {}

func (x *IssueA2ABadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueA2ABadgeRequest.ProtoReflect.Descriptor instead.
func (*IssueA2ABadgeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssueA2ABadgeRequest) GetWellKnownUrl() string {
	if x != nil && x.WellKnownUrl != nil {
		return *x.WellKnownUrl
	}
	return ""
}

func (x *IssueA2ABadgeRequest) GetSchemaBase64() string {
	if x != nil && x.SchemaBase64 != nil {
		return *x.SchemaBase64
	}
	return ""
}

type IssueOASFBadgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OASF schema in a base64 encoded format
	SchemaBase64  string `protobuf:"bytes,1,opt,name=schema_base64,json=schemaBase64,proto3" json:"schema_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueOASFBadgeRequest) Reset() {
	*x = IssueOASFBadgeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueOASFBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueOASFBadgeRequest) ProtoMessage() {}

func (x *IssueOASFBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueOASFBadgeRequest.ProtoReflect.Descriptor instead.
func (*IssueOASFBadgeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP(), []int{3}
}

func (x *IssueOASFBadgeRequest) GetSchemaBase64() string {
	if x != nil {
		return x.SchemaBase64
	}
	return ""
}

type VerifyBadgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JOSE enveloped badge to verify.
	Badge         string `protobuf:"bytes,1,opt,name=badge,proto3" json:"badge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBadgeRequest) Reset() {
	*x = VerifyBadgeRequest{}
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBadgeRequest) ProtoMessage() {}

func (x *VerifyBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBadgeRequest.ProtoReflect.Descriptor instead.
func (*VerifyBadgeRequest) Descriptor() ([]byte, []int) {
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyBadgeRequest) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

var File_outshift_identity_service_v1alpha1_badge_service_proto protoreflect.FileDescriptor

const file_outshift_identity_service_v1alpha1_badge_service_proto_rawDesc = "" +
	"\n" +
	"6outshift/identity/service/v1alpha1/badge_service.proto\x12\"outshift.identity.service.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a.outshift/identity/service/v1alpha1/badge.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x91\x02\n" +
	"\x11IssueBadgeRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12J\n" +
	"\x03a2a\x18\x02 \x01(\v28.outshift.identity.service.v1alpha1.IssueA2ABadgeRequestR\x03a2a\x12J\n" +
	"\x03mcp\x18\x03 \x01(\v28.outshift.identity.service.v1alpha1.IssueMcpBadgeRequestR\x03mcp\x12M\n" +
	"\x04oasf\x18\x04 \x01(\v29.outshift.identity.service.v1alpha1.IssueOASFBadgeRequestR\x04oasf\"\x93\x01\n" +
	"\x14IssueMcpBadgeRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x01R\x03url\x88\x01\x01\x12(\n" +
	"\rschema_base64\x18\x03 \x01(\tH\x02R\fschemaBase64\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_urlB\x10\n" +
	"\x0e_schema_base64\"\x90\x01\n" +
	"\x14IssueA2ABadgeRequest\x12)\n" +
	"\x0ewell_known_url\x18\x01 \x01(\tH\x00R\fwellKnownUrl\x88\x01\x01\x12(\n" +
	"\rschema_base64\x18\x02 \x01(\tH\x01R\fschemaBase64\x88\x01\x01B\x11\n" +
	"\x0f_well_known_urlB\x10\n" +
	"\x0e_schema_base64\"<\n" +
	"\x15IssueOASFBadgeRequest\x12#\n" +
	"\rschema_base64\x18\x01 \x01(\tR\fschemaBase64\"*\n" +
	"\x12VerifyBadgeRequest\x12\x14\n" +
	"\x05badge\x18\x01 \x01(\tR\x05badge2\x98\x03\n" +
	"\fBadgeService\x12\xb7\x01\n" +
	"\n" +
	"IssueBadge\x125.outshift.identity.service.v1alpha1.IssueBadgeRequest\x1a).outshift.identity.service.v1alpha1.Badge\"G\x92A\x1b\x12\rIssue a badge*\n" +
	"IssueBadge\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1alpha1/apps/{app_id}/badges\x12\xc1\x01\n" +
	"\vVerifyBadge\x126.outshift.identity.service.v1alpha1.VerifyBadgeRequest\x1a6.outshift.identity.service.v1alpha1.VerificationResult\"B\x92A\x1d\x12\x0eVerify a badge*\vVerifyBadge\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1alpha1/badges/verify\x1a\n" +
	"\x92A\a\n" +
	"\x05BadgeBlZjgithub.com/outshift/identity-service/api/server/outshift/identity/service/v1alpha1;identity_service_sdk_gob\x06proto3"

var (
	file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescOnce sync.Once
	file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescData []byte
)

func file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescGZIP() []byte {
	file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescOnce.Do(func() {
		file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_badge_service_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_badge_service_proto_rawDesc)))
	})
	return file_outshift_identity_service_v1alpha1_badge_service_proto_rawDescData
}

var file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_outshift_identity_service_v1alpha1_badge_service_proto_goTypes = []any{
	(*IssueBadgeRequest)(nil),     // 0: outshift.identity.service.v1alpha1.IssueBadgeRequest
	(*IssueMcpBadgeRequest)(nil),  // 1: outshift.identity.service.v1alpha1.IssueMcpBadgeRequest
	(*IssueA2ABadgeRequest)(nil),  // 2: outshift.identity.service.v1alpha1.IssueA2ABadgeRequest
	(*IssueOASFBadgeRequest)(nil), // 3: outshift.identity.service.v1alpha1.IssueOASFBadgeRequest
	(*VerifyBadgeRequest)(nil),    // 4: outshift.identity.service.v1alpha1.VerifyBadgeRequest
	(*Badge)(nil),                 // 5: outshift.identity.service.v1alpha1.Badge
	(*VerificationResult)(nil),    // 6: outshift.identity.service.v1alpha1.VerificationResult
}
var file_outshift_identity_service_v1alpha1_badge_service_proto_depIdxs = []int32{
	2, // 0: outshift.identity.service.v1alpha1.IssueBadgeRequest.a2a:type_name -> outshift.identity.service.v1alpha1.IssueA2ABadgeRequest
	1, // 1: outshift.identity.service.v1alpha1.IssueBadgeRequest.mcp:type_name -> outshift.identity.service.v1alpha1.IssueMcpBadgeRequest
	3, // 2: outshift.identity.service.v1alpha1.IssueBadgeRequest.oasf:type_name -> outshift.identity.service.v1alpha1.IssueOASFBadgeRequest
	0, // 3: outshift.identity.service.v1alpha1.BadgeService.IssueBadge:input_type -> outshift.identity.service.v1alpha1.IssueBadgeRequest
	4, // 4: outshift.identity.service.v1alpha1.BadgeService.VerifyBadge:input_type -> outshift.identity.service.v1alpha1.VerifyBadgeRequest
	5, // 5: outshift.identity.service.v1alpha1.BadgeService.IssueBadge:output_type -> outshift.identity.service.v1alpha1.Badge
	6, // 6: outshift.identity.service.v1alpha1.BadgeService.VerifyBadge:output_type -> outshift.identity.service.v1alpha1.VerificationResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_outshift_identity_service_v1alpha1_badge_service_proto_init() }
func file_outshift_identity_service_v1alpha1_badge_service_proto_init() {
	if File_outshift_identity_service_v1alpha1_badge_service_proto != nil {
		return
	}
	file_outshift_identity_service_v1alpha1_badge_proto_init()
	file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_badge_service_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_badge_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outshift_identity_service_v1alpha1_badge_service_proto_goTypes,
		DependencyIndexes: file_outshift_identity_service_v1alpha1_badge_service_proto_depIdxs,
		MessageInfos:      file_outshift_identity_service_v1alpha1_badge_service_proto_msgTypes,
	}.Build()
	File_outshift_identity_service_v1alpha1_badge_service_proto = out.File
	file_outshift_identity_service_v1alpha1_badge_service_proto_goTypes = nil
	file_outshift_identity_service_v1alpha1_badge_service_proto_depIdxs = nil
}
