// Copyright 2025 Cisco Systems, Inc. and its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: outshift/identity/service/v1alpha1/openapi_v2.proto

package identity_service_sdk_go

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_outshift_identity_service_v1alpha1_openapi_v2_proto protoreflect.FileDescriptor

const file_outshift_identity_service_v1alpha1_openapi_v2_proto_rawDesc = "" +
	"\n" +
	"3outshift/identity/service/v1alpha1/openapi_v2.proto\x12\"outshift.identity.service.v1alpha1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xa1\x04\x92A\xb1\x03\x12\x81\x02\n" +
	"\x1aAgent Identity Service API\x12~Agent Identity Service API provides a set of endpoints for managing identity and access control within the Outshift ecosystem.\"Y\n" +
	"\rOutshift Team\x121https://github.com/outshift-open/identity-service\x1a\x15identity@outshift.com2\bv1alpha1Z\x8b\x01\n" +
	"Z\n" +
	"\vAccessToken\x12K\b\x02\x126An IAM JWT token issued to a user during an OIDC flow.\x1a\rAuthorization \x02\n" +
	"-\n" +
	"\x06ApiKey\x12#\b\x02\x12\x0fAn IAM Api key.\x1a\fx-id-api-key \x02b\x1d\n" +
	"\x0f\n" +
	"\vAccessToken\x12\x00\n" +
	"\n" +
	"\n" +
	"\x06ApiKey\x12\x00Zjgithub.com/outshift/identity-service/api/server/outshift/identity/service/v1alpha1;identity_service_sdk_gob\x06proto3"

var file_outshift_identity_service_v1alpha1_openapi_v2_proto_goTypes = []any{}
var file_outshift_identity_service_v1alpha1_openapi_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outshift_identity_service_v1alpha1_openapi_v2_proto_init() }
func file_outshift_identity_service_v1alpha1_openapi_v2_proto_init() {
	if File_outshift_identity_service_v1alpha1_openapi_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_openapi_v2_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_openapi_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outshift_identity_service_v1alpha1_openapi_v2_proto_goTypes,
		DependencyIndexes: file_outshift_identity_service_v1alpha1_openapi_v2_proto_depIdxs,
	}.Build()
	File_outshift_identity_service_v1alpha1_openapi_v2_proto = out.File
	file_outshift_identity_service_v1alpha1_openapi_v2_proto_goTypes = nil
	file_outshift_identity_service_v1alpha1_openapi_v2_proto_depIdxs = nil
}
