// Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: outshift/identity/service/v1alpha1/openapi.proto

package identity_service_sdk_go

import (
	_ "github.com/google/gnostic-models/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_outshift_identity_service_v1alpha1_openapi_proto protoreflect.FileDescriptor

const file_outshift_identity_service_v1alpha1_openapi_proto_rawDesc = "" +
	"\n" +
	"0outshift/identity/service/v1alpha1/openapi.proto\x12\"outshift.identity.service.v1alpha1\x1a\x1bopenapiv3/annotations.protoB\xd5\x04\xbaG\xe5\x03\x12\xf2\x01\n" +
	"\x1aAgent Identity Service API\x12~Agent Identity Service API provides a set of endpoints for managing identity and access control within the Outshift ecosystem.\"J\n" +
	"\rOutshift Team\x12\"https://github.com/agntcy/identity\x1a\x15identity@outshift.com2\bv1alpha1\x1a*\n" +
	"\x15http://localhost:4000\x12\x11Local environment*\xa2\x012\x02\n" +
	"\x00:\x9b\x01\n" +
	"\\\n" +
	"\vAccessToken\x12M\n" +
	"K\n" +
	"\x04http\x126An IAM JWT token issued to a user during an OIDC flow.*\x06bearer2\x03JWT\n" +
	";\n" +
	"\x06ApiKey\x121\n" +
	"/\n" +
	"\x06apiKey\x12\x0fAn IAM Api key.\x1a\fx-id-api-key\"\x06header2\x1d\n" +
	"\x0f\n" +
	"\vAccessToken\x12\x00\n" +
	"\n" +
	"\n" +
	"\x06ApiKey\x12\x00Zjgithub.com/outshift/identity-service/api/server/outshift/identity/service/v1alpha1;identity_service_sdk_gob\x06proto3"

var file_outshift_identity_service_v1alpha1_openapi_proto_goTypes = []any{}
var file_outshift_identity_service_v1alpha1_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outshift_identity_service_v1alpha1_openapi_proto_init() }
func file_outshift_identity_service_v1alpha1_openapi_proto_init() {
	if File_outshift_identity_service_v1alpha1_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outshift_identity_service_v1alpha1_openapi_proto_rawDesc), len(file_outshift_identity_service_v1alpha1_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outshift_identity_service_v1alpha1_openapi_proto_goTypes,
		DependencyIndexes: file_outshift_identity_service_v1alpha1_openapi_proto_depIdxs,
	}.Build()
	File_outshift_identity_service_v1alpha1_openapi_proto = out.File
	file_outshift_identity_service_v1alpha1_openapi_proto_goTypes = nil
	file_outshift_identity_service_v1alpha1_openapi_proto_depIdxs = nil
}
