// Code generated by go-swagger; DO NOT EDIT.

package badge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity-service/backend/api/client/models"
)

// NewIssueBadgeParams creates a new IssueBadgeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIssueBadgeParams() *IssueBadgeParams {
	return &IssueBadgeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIssueBadgeParamsWithTimeout creates a new IssueBadgeParams object
// with the ability to set a timeout on a request.
func NewIssueBadgeParamsWithTimeout(timeout time.Duration) *IssueBadgeParams {
	return &IssueBadgeParams{
		timeout: timeout,
	}
}

// NewIssueBadgeParamsWithContext creates a new IssueBadgeParams object
// with the ability to set a context for a request.
func NewIssueBadgeParamsWithContext(ctx context.Context) *IssueBadgeParams {
	return &IssueBadgeParams{
		Context: ctx,
	}
}

// NewIssueBadgeParamsWithHTTPClient creates a new IssueBadgeParams object
// with the ability to set a custom HTTPClient for a request.
func NewIssueBadgeParamsWithHTTPClient(client *http.Client) *IssueBadgeParams {
	return &IssueBadgeParams{
		HTTPClient: client,
	}
}

/*
IssueBadgeParams contains all the parameters to send to the API endpoint

	for the issue badge operation.

	Typically these are written to a http.Request.
*/
type IssueBadgeParams struct {

	/* AppID.

	   App Id.
	*/
	AppID string

	// Body.
	Body *models.BadgeServiceIssueBadgeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the issue badge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueBadgeParams) WithDefaults() *IssueBadgeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the issue badge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IssueBadgeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the issue badge params
func (o *IssueBadgeParams) WithTimeout(timeout time.Duration) *IssueBadgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue badge params
func (o *IssueBadgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue badge params
func (o *IssueBadgeParams) WithContext(ctx context.Context) *IssueBadgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue badge params
func (o *IssueBadgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue badge params
func (o *IssueBadgeParams) WithHTTPClient(client *http.Client) *IssueBadgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue badge params
func (o *IssueBadgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the issue badge params
func (o *IssueBadgeParams) WithAppID(appID string) *IssueBadgeParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the issue badge params
func (o *IssueBadgeParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithBody adds the body to the issue badge params
func (o *IssueBadgeParams) WithBody(body *models.BadgeServiceIssueBadgeBody) *IssueBadgeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the issue badge params
func (o *IssueBadgeParams) SetBody(body *models.BadgeServiceIssueBadgeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IssueBadgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
