// Code generated by go-swagger; DO NOT EDIT.

package badge

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity-service/backend/api/client/models"
)

// VerifyBadgeReader is a Reader for the VerifyBadge structure.
type VerifyBadgeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyBadgeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyBadgeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyBadgeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyBadgeOK creates a VerifyBadgeOK with default headers values
func NewVerifyBadgeOK() *VerifyBadgeOK {
	return &VerifyBadgeOK{}
}

/*
VerifyBadgeOK describes a response with status code 200, with default header values.

A successful response.
*/
type VerifyBadgeOK struct {
	Payload *models.V1alpha1VerificationResult
}

// IsSuccess returns true when this verify badge o k response has a 2xx status code
func (o *VerifyBadgeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this verify badge o k response has a 3xx status code
func (o *VerifyBadgeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify badge o k response has a 4xx status code
func (o *VerifyBadgeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this verify badge o k response has a 5xx status code
func (o *VerifyBadgeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this verify badge o k response a status code equal to that given
func (o *VerifyBadgeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the verify badge o k response
func (o *VerifyBadgeOK) Code() int {
	return 200
}

func (o *VerifyBadgeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/badges/verify][%d] verifyBadgeOK %s", 200, payload)
}

func (o *VerifyBadgeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/badges/verify][%d] verifyBadgeOK %s", 200, payload)
}

func (o *VerifyBadgeOK) GetPayload() *models.V1alpha1VerificationResult {
	return o.Payload
}

func (o *VerifyBadgeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1VerificationResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewVerifyBadgeDefault creates a VerifyBadgeDefault with default headers values
func NewVerifyBadgeDefault(code int) *VerifyBadgeDefault {
	return &VerifyBadgeDefault{
		_statusCode: code,
	}
}

/*
VerifyBadgeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type VerifyBadgeDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this verify badge default response has a 2xx status code
func (o *VerifyBadgeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this verify badge default response has a 3xx status code
func (o *VerifyBadgeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this verify badge default response has a 4xx status code
func (o *VerifyBadgeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this verify badge default response has a 5xx status code
func (o *VerifyBadgeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this verify badge default response a status code equal to that given
func (o *VerifyBadgeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the verify badge default response
func (o *VerifyBadgeDefault) Code() int {
	return o._statusCode
}

func (o *VerifyBadgeDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/badges/verify][%d] VerifyBadge default %s", o._statusCode, payload)
}

func (o *VerifyBadgeDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/badges/verify][%d] VerifyBadge default %s", o._statusCode, payload)
}

func (o *VerifyBadgeDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *VerifyBadgeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
