// Code generated by go-swagger; DO NOT EDIT.

package app

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity-service/backend/api/client/models"
)

// NewCreateOasfAppParams creates a new CreateOasfAppParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateOasfAppParams() *CreateOasfAppParams {
	return &CreateOasfAppParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOasfAppParamsWithTimeout creates a new CreateOasfAppParams object
// with the ability to set a timeout on a request.
func NewCreateOasfAppParamsWithTimeout(timeout time.Duration) *CreateOasfAppParams {
	return &CreateOasfAppParams{
		timeout: timeout,
	}
}

// NewCreateOasfAppParamsWithContext creates a new CreateOasfAppParams object
// with the ability to set a context for a request.
func NewCreateOasfAppParamsWithContext(ctx context.Context) *CreateOasfAppParams {
	return &CreateOasfAppParams{
		Context: ctx,
	}
}

// NewCreateOasfAppParamsWithHTTPClient creates a new CreateOasfAppParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateOasfAppParamsWithHTTPClient(client *http.Client) *CreateOasfAppParams {
	return &CreateOasfAppParams{
		HTTPClient: client,
	}
}

/*
CreateOasfAppParams contains all the parameters to send to the API endpoint

	for the create oasf app operation.

	Typically these are written to a http.Request.
*/
type CreateOasfAppParams struct {

	// Body.
	Body *models.V1alpha1CreateOasfAppRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create oasf app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOasfAppParams) WithDefaults() *CreateOasfAppParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create oasf app params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOasfAppParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create oasf app params
func (o *CreateOasfAppParams) WithTimeout(timeout time.Duration) *CreateOasfAppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create oasf app params
func (o *CreateOasfAppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create oasf app params
func (o *CreateOasfAppParams) WithContext(ctx context.Context) *CreateOasfAppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create oasf app params
func (o *CreateOasfAppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create oasf app params
func (o *CreateOasfAppParams) WithHTTPClient(client *http.Client) *CreateOasfAppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create oasf app params
func (o *CreateOasfAppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create oasf app params
func (o *CreateOasfAppParams) WithBody(body *models.V1alpha1CreateOasfAppRequest) *CreateOasfAppParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create oasf app params
func (o *CreateOasfAppParams) SetBody(body *models.V1alpha1CreateOasfAppRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOasfAppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
