// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAppBadgeParams creates a new GetAppBadgeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAppBadgeParams() *GetAppBadgeParams {
	return &GetAppBadgeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppBadgeParamsWithTimeout creates a new GetAppBadgeParams object
// with the ability to set a timeout on a request.
func NewGetAppBadgeParamsWithTimeout(timeout time.Duration) *GetAppBadgeParams {
	return &GetAppBadgeParams{
		timeout: timeout,
	}
}

// NewGetAppBadgeParamsWithContext creates a new GetAppBadgeParams object
// with the ability to set a context for a request.
func NewGetAppBadgeParamsWithContext(ctx context.Context) *GetAppBadgeParams {
	return &GetAppBadgeParams{
		Context: ctx,
	}
}

// NewGetAppBadgeParamsWithHTTPClient creates a new GetAppBadgeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAppBadgeParamsWithHTTPClient(client *http.Client) *GetAppBadgeParams {
	return &GetAppBadgeParams{
		HTTPClient: client,
	}
}

/*
GetAppBadgeParams contains all the parameters to send to the API endpoint

	for the get app badge operation.

	Typically these are written to a http.Request.
*/
type GetAppBadgeParams struct {

	/* AppID.

	   App Id to get the badge for.
	*/
	AppID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get app badge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppBadgeParams) WithDefaults() *GetAppBadgeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get app badge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppBadgeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get app badge params
func (o *GetAppBadgeParams) WithTimeout(timeout time.Duration) *GetAppBadgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app badge params
func (o *GetAppBadgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app badge params
func (o *GetAppBadgeParams) WithContext(ctx context.Context) *GetAppBadgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app badge params
func (o *GetAppBadgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app badge params
func (o *GetAppBadgeParams) WithHTTPClient(client *http.Client) *GetAppBadgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app badge params
func (o *GetAppBadgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the get app badge params
func (o *GetAppBadgeParams) WithAppID(appID string) *GetAppBadgeParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get app badge params
func (o *GetAppBadgeParams) SetAppID(appID string) {
	o.AppID = appID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppBadgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
