// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/outshift/identity-service/api/client/models"
)

// GetAppBadgeReader is a Reader for the GetAppBadge structure.
type GetAppBadgeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppBadgeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAppBadgeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAppBadgeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAppBadgeOK creates a GetAppBadgeOK with default headers values
func NewGetAppBadgeOK() *GetAppBadgeOK {
	return &GetAppBadgeOK{}
}

/*
GetAppBadgeOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetAppBadgeOK struct {
	Payload *models.V1alpha1Badge
}

// IsSuccess returns true when this get app badge o k response has a 2xx status code
func (o *GetAppBadgeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get app badge o k response has a 3xx status code
func (o *GetAppBadgeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app badge o k response has a 4xx status code
func (o *GetAppBadgeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get app badge o k response has a 5xx status code
func (o *GetAppBadgeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get app badge o k response a status code equal to that given
func (o *GetAppBadgeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get app badge o k response
func (o *GetAppBadgeOK) Code() int {
	return 200
}

func (o *GetAppBadgeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/{appId}/badge][%d] getAppBadgeOK %s", 200, payload)
}

func (o *GetAppBadgeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/{appId}/badge][%d] getAppBadgeOK %s", 200, payload)
}

func (o *GetAppBadgeOK) GetPayload() *models.V1alpha1Badge {
	return o.Payload
}

func (o *GetAppBadgeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Badge)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBadgeDefault creates a GetAppBadgeDefault with default headers values
func NewGetAppBadgeDefault(code int) *GetAppBadgeDefault {
	return &GetAppBadgeDefault{
		_statusCode: code,
	}
}

/*
GetAppBadgeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetAppBadgeDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get app badge default response has a 2xx status code
func (o *GetAppBadgeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get app badge default response has a 3xx status code
func (o *GetAppBadgeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get app badge default response has a 4xx status code
func (o *GetAppBadgeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get app badge default response has a 5xx status code
func (o *GetAppBadgeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get app badge default response a status code equal to that given
func (o *GetAppBadgeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get app badge default response
func (o *GetAppBadgeDefault) Code() int {
	return o._statusCode
}

func (o *GetAppBadgeDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/{appId}/badge][%d] GetAppBadge default %s", o._statusCode, payload)
}

func (o *GetAppBadgeDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/{appId}/badge][%d] GetAppBadge default %s", o._statusCode, payload)
}

func (o *GetAppBadgeDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetAppBadgeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
