// Code generated by go-swagger; DO NOT EDIT.

package app

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/agntcy/identity-service/backend/api/client/models"
)

// GetAppsCountReader is a Reader for the GetAppsCount structure.
type GetAppsCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppsCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAppsCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAppsCountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAppsCountOK creates a GetAppsCountOK with default headers values
func NewGetAppsCountOK() *GetAppsCountOK {
	return &GetAppsCountOK{}
}

/*
GetAppsCountOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetAppsCountOK struct {
	Payload *models.V1alpha1GetAppsCountResponse
}

// IsSuccess returns true when this get apps count o k response has a 2xx status code
func (o *GetAppsCountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get apps count o k response has a 3xx status code
func (o *GetAppsCountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get apps count o k response has a 4xx status code
func (o *GetAppsCountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get apps count o k response has a 5xx status code
func (o *GetAppsCountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get apps count o k response a status code equal to that given
func (o *GetAppsCountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get apps count o k response
func (o *GetAppsCountOK) Code() int {
	return 200
}

func (o *GetAppsCountOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/all/count][%d] getAppsCountOK %s", 200, payload)
}

func (o *GetAppsCountOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/all/count][%d] getAppsCountOK %s", 200, payload)
}

func (o *GetAppsCountOK) GetPayload() *models.V1alpha1GetAppsCountResponse {
	return o.Payload
}

func (o *GetAppsCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1GetAppsCountResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppsCountDefault creates a GetAppsCountDefault with default headers values
func NewGetAppsCountDefault(code int) *GetAppsCountDefault {
	return &GetAppsCountDefault{
		_statusCode: code,
	}
}

/*
GetAppsCountDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetAppsCountDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get apps count default response has a 2xx status code
func (o *GetAppsCountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get apps count default response has a 3xx status code
func (o *GetAppsCountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get apps count default response has a 4xx status code
func (o *GetAppsCountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get apps count default response has a 5xx status code
func (o *GetAppsCountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get apps count default response a status code equal to that given
func (o *GetAppsCountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get apps count default response
func (o *GetAppsCountDefault) Code() int {
	return o._statusCode
}

func (o *GetAppsCountDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/all/count][%d] GetAppsCount default %s", o._statusCode, payload)
}

func (o *GetAppsCountDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/apps/all/count][%d] GetAppsCount default %s", o._statusCode, payload)
}

func (o *GetAppsCountDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetAppsCountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
