# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  go: 1.24.1
  issues-exit-code: 1
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
    gomoddirectives:
      replace-local: true
    gosec:
      excludes:
        - G115
    interfacebloat:
      max: 11
    nestif:
      min-complexity: 10
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      severity: warning
    wsl:
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
      force-err-cuddling: true
      force-short-decl-cuddling: false
    funlen:
      statements: 100
      lines: 200
    unused:
      # Mark all struct fields that have been written to as used.
      field-writes-are-uses: false
      # Treat IncDec statement (e.g. `i++` or `i--`) as both read and write operation instead of just write.
      post-statements-are-reads: true
      # Mark all exported fields as used.
      exported-fields-are-used: false
      # Mark all local variables as used.
      local-variables-are-used: false
      # Mark all identifiers inside generated files as used.
      generated-is-used: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1000:'
    paths:
      - third_party$
      - builtin$
      - examples$
      - api
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
