// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/outshift-open/identity-service/backend/api/client/models"
)

// RegisterDeviceReader is a Reader for the RegisterDevice structure.
type RegisterDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRegisterDeviceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRegisterDeviceOK creates a RegisterDeviceOK with default headers values
func NewRegisterDeviceOK() *RegisterDeviceOK {
	return &RegisterDeviceOK{}
}

/*
RegisterDeviceOK describes a response with status code 200, with default header values.

A successful response.
*/
type RegisterDeviceOK struct {
	Payload any
}

// IsSuccess returns true when this register device o k response has a 2xx status code
func (o *RegisterDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register device o k response has a 3xx status code
func (o *RegisterDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register device o k response has a 4xx status code
func (o *RegisterDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this register device o k response has a 5xx status code
func (o *RegisterDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this register device o k response a status code equal to that given
func (o *RegisterDeviceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the register device o k response
func (o *RegisterDeviceOK) Code() int {
	return 200
}

func (o *RegisterDeviceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/device/{deviceId}][%d] registerDeviceOK %s", 200, payload)
}

func (o *RegisterDeviceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/device/{deviceId}][%d] registerDeviceOK %s", 200, payload)
}

func (o *RegisterDeviceOK) GetPayload() any {
	return o.Payload
}

func (o *RegisterDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRegisterDeviceDefault creates a RegisterDeviceDefault with default headers values
func NewRegisterDeviceDefault(code int) *RegisterDeviceDefault {
	return &RegisterDeviceDefault{
		_statusCode: code,
	}
}

/*
RegisterDeviceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RegisterDeviceDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this register device default response has a 2xx status code
func (o *RegisterDeviceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this register device default response has a 3xx status code
func (o *RegisterDeviceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this register device default response has a 4xx status code
func (o *RegisterDeviceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this register device default response has a 5xx status code
func (o *RegisterDeviceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this register device default response a status code equal to that given
func (o *RegisterDeviceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the register device default response
func (o *RegisterDeviceDefault) Code() int {
	return o._statusCode
}

func (o *RegisterDeviceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/device/{deviceId}][%d] RegisterDevice default %s", o._statusCode, payload)
}

func (o *RegisterDeviceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1alpha1/device/{deviceId}][%d] RegisterDevice default %s", o._statusCode, payload)
}

func (o *RegisterDeviceDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RegisterDeviceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
