# Copyright 2025 Example Organization Contributors (https://github.com/example-org)
# SPDX-License-Identifier: Apache-2.0

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

namespace: identity-service-dev

imagePullSecrets:
  - name: ecr-credentials

service:
  type: ClusterIP
  http:
    port: 80
    targetPort: 80

ingress:
  enabled: true
  className: nginx-internal
  annotations:
    http:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt

  domainPrefixHttp: identity-service-docs
  apiDomainName: example.domain.com

serviceAccount:
  create: true
  name: ""
