// Code generated by "stringer -type=AppType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APP_TYPE_UNSPECIFIED-0]
	_ = x[APP_TYPE_AGENT_A2A-1]
	_ = x[APP_TYPE_AGENT_OASF-2]
	_ = x[APP_TYPE_MCP_SERVER-3]
}

const _AppType_name = "APP_TYPE_UNSPECIFIEDAPP_TYPE_AGENT_A2AAPP_TYPE_AGENT_OASFAPP_TYPE_MCP_SERVER"

var _AppType_index = [...]uint8{0, 20, 38, 57, 76}

func (i AppType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AppType_index)-1 {
		return "AppType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppType_name[_AppType_index[idx]:_AppType_index[idx+1]]
}
