// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/outshift/identity-service/api/client/models"
)

// GetSettingsReader is a Reader for the GetSettings structure.
type GetSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSettingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSettingsOK creates a GetSettingsOK with default headers values
func NewGetSettingsOK() *GetSettingsOK {
	return &GetSettingsOK{}
}

/*
GetSettingsOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetSettingsOK struct {
	Payload *models.V1alpha1Settings
}

// IsSuccess returns true when this get settings o k response has a 2xx status code
func (o *GetSettingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get settings o k response has a 3xx status code
func (o *GetSettingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get settings o k response has a 4xx status code
func (o *GetSettingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get settings o k response has a 5xx status code
func (o *GetSettingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get settings o k response a status code equal to that given
func (o *GetSettingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get settings o k response
func (o *GetSettingsOK) Code() int {
	return 200
}

func (o *GetSettingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/settings][%d] getSettingsOK %s", 200, payload)
}

func (o *GetSettingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/settings][%d] getSettingsOK %s", 200, payload)
}

func (o *GetSettingsOK) GetPayload() *models.V1alpha1Settings {
	return o.Payload
}

func (o *GetSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Settings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSettingsDefault creates a GetSettingsDefault with default headers values
func NewGetSettingsDefault(code int) *GetSettingsDefault {
	return &GetSettingsDefault{
		_statusCode: code,
	}
}

/*
GetSettingsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetSettingsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this get settings default response has a 2xx status code
func (o *GetSettingsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get settings default response has a 3xx status code
func (o *GetSettingsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get settings default response has a 4xx status code
func (o *GetSettingsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get settings default response has a 5xx status code
func (o *GetSettingsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get settings default response a status code equal to that given
func (o *GetSettingsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get settings default response
func (o *GetSettingsDefault) Code() int {
	return o._statusCode
}

func (o *GetSettingsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/settings][%d] Get Settings default %s", o._statusCode, payload)
}

func (o *GetSettingsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1alpha1/settings][%d] Get Settings default %s", o._statusCode, payload)
}

func (o *GetSettingsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *GetSettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
