// Code generated by "stringer --type BadgeType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BADGE_TYPE_UNSPECIFIED-0]
	_ = x[BADGE_TYPE_AGENT_BADGE-1]
	_ = x[BADGE_TYPE_MCP_BADGE-2]
}

const _BadgeType_name = "BADGE_TYPE_UNSPECIFIEDBADGE_TYPE_AGENT_BADGEBADGE_TYPE_MCP_BADGE"

var _BadgeType_index = [...]uint8{0, 22, 44, 64}

func (i BadgeType) String() string {
	if i < 0 || i >= BadgeType(len(_BadgeType_index)-1) {
		return "BadgeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BadgeType_name[_BadgeType_index[i]:_BadgeType_index[i+1]]
}
