compressionLevel: mixed

enableGlobalCache: false

injectEnvironmentFiles:
  - .env

nodeLinker: node-modules

npmScopes:
  outshift:
    npmAlwaysAuth: true
    npmAuthToken: "${ARTIFACTORY_PASSWORD}"
    npmRegistryServer: "https://artifactory.devhub-cloud.cisco.com/artifactory/api/npm/outshift-npm/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
