// Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/platform/v1alpha1/auth_service.proto

package identity_platform_sdk_go

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The App information.
	App           *App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfoResponse) Reset() {
	*x = AppInfoResponse{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfoResponse) ProtoMessage() {}

func (x *AppInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfoResponse.ProtoReflect.Descriptor instead.
func (*AppInfoResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppInfoResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The app for which authorization is requested.
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// The MCP Server tool name.
	ToolName *string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3,oneof" json:"tool_name,omitempty"`
	// The User context in the form of an id or access token.
	// Mandatory for User Approval Flows.
	UserToken     *string `protobuf:"bytes,3,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *AuthorizeRequest) GetToolName() string {
	if x != nil && x.ToolName != nil {
		return *x.ToolName
	}
	return ""
}

func (x *AuthorizeRequest) GetUserToken() string {
	if x != nil && x.UserToken != nil {
		return *x.UserToken
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If authorization is successful, return a code to be used for
	// the token endpoint.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pass the code received from the authorization endpoint.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token issued to the Agent or MCP Server.
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RegisterDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The User context in the form of an id or access token.
	// Mandatory for User Approval Flows.
	UserToken string `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	// The device information to register.
	Device        *Device `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterDeviceRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_agntcy_identity_platform_v1alpha1_auth_service_proto protoreflect.FileDescriptor

const file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDesc = "" +
	"\n" +
	"4agntcy/identity/platform/v1alpha1/auth_service.proto\x12!agntcy.identity.platform.v1alpha1\x1a+agntcy/identity/platform/v1alpha1/app.proto\x1a,agntcy/identity/platform/v1alpha1/auth.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"K\n" +
	"\x0fAppInfoResponse\x128\n" +
	"\x03app\x18\x01 \x01(\v2&.agntcy.identity.platform.v1alpha1.AppR\x03app\"\x87\x01\n" +
	"\x10AuthorizeRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12 \n" +
	"\ttool_name\x18\x02 \x01(\tH\x00R\btoolName\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_token\x18\x03 \x01(\tH\x01R\tuserToken\x88\x01\x01B\f\n" +
	"\n" +
	"_tool_nameB\r\n" +
	"\v_user_token\"'\n" +
	"\x11AuthorizeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\"\n" +
	"\fTokenRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"O\n" +
	"\rTokenResponse\x12>\n" +
	"\x05token\x18\x01 \x01(\v2(.agntcy.identity.platform.v1alpha1.TokenR\x05token\"y\n" +
	"\x15RegisterDeviceRequest\x12\x1d\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tR\tuserToken\x12A\n" +
	"\x06device\x18\x02 \x01(\v2).agntcy.identity.platform.v1alpha1.DeviceR\x06device2\xab\a\n" +
	"\vAuthService\x12\x90\x01\n" +
	"\aAppInfo\x12\x16.google.protobuf.Empty\x1a2.agntcy.identity.platform.v1alpha1.AppInfoResponse\"9\x92A\x17\x12\fGet App Info*\aAppInfo\x82\xd3\xe4\x93\x02\x19\x12\x17/v1alpha1/auth/app_info\x12\xd7\x01\n" +
	"\tAuthorize\x123.agntcy.identity.platform.v1alpha1.AuthorizeRequest\x1a4.agntcy.identity.platform.v1alpha1.AuthorizeResponse\"_\x92A<\x12/Authorize a request from an Agent or MCP Server*\tAuthorize\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1alpha1/auth/authorize\x12\xc3\x01\n" +
	"\x05Token\x12/.agntcy.identity.platform.v1alpha1.TokenRequest\x1a0.agntcy.identity.platform.v1alpha1.TokenResponse\"W\x92A8\x12(Request token for an Agent or MCP Server*\fRequestToken\x82\xd3\xe4\x93\x02\x16\"\x14/v1alpha1/auth/token\x12\x91\x01\n" +
	"\bExtAuthz\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"U\x92A2\x12&Handle external authorization requests*\bExtAuthz\x82\xd3\xe4\x93\x02\x1a\"\x18/v1alpha1/auth/ext_authz\x12\xc9\x01\n" +
	"\x0eRegisterDevice\x128.agntcy.identity.platform.v1alpha1.RegisterDeviceRequest\x1a\x16.google.protobuf.Empty\"e\x92A<\x12*Register new user device for approval flow*\x0eRegisterDevice\x82\xd3\xe4\x93\x02 \"\x1e/v1alpha1/auth/register_device\x1a\t\x92A\x06\n" +
	"\x04AuthBkZigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_gob\x06proto3"

var (
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescOnce sync.Once
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescData []byte
)

func file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescGZIP() []byte {
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDesc)))
	})
	return file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDescData
}

var file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agntcy_identity_platform_v1alpha1_auth_service_proto_goTypes = []any{
	(*AppInfoResponse)(nil),       // 0: agntcy.identity.platform.v1alpha1.AppInfoResponse
	(*AuthorizeRequest)(nil),      // 1: agntcy.identity.platform.v1alpha1.AuthorizeRequest
	(*AuthorizeResponse)(nil),     // 2: agntcy.identity.platform.v1alpha1.AuthorizeResponse
	(*TokenRequest)(nil),          // 3: agntcy.identity.platform.v1alpha1.TokenRequest
	(*TokenResponse)(nil),         // 4: agntcy.identity.platform.v1alpha1.TokenResponse
	(*RegisterDeviceRequest)(nil), // 5: agntcy.identity.platform.v1alpha1.RegisterDeviceRequest
	(*App)(nil),                   // 6: agntcy.identity.platform.v1alpha1.App
	(*Token)(nil),                 // 7: agntcy.identity.platform.v1alpha1.Token
	(*Device)(nil),                // 8: agntcy.identity.platform.v1alpha1.Device
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_agntcy_identity_platform_v1alpha1_auth_service_proto_depIdxs = []int32{
	6, // 0: agntcy.identity.platform.v1alpha1.AppInfoResponse.app:type_name -> agntcy.identity.platform.v1alpha1.App
	7, // 1: agntcy.identity.platform.v1alpha1.TokenResponse.token:type_name -> agntcy.identity.platform.v1alpha1.Token
	8, // 2: agntcy.identity.platform.v1alpha1.RegisterDeviceRequest.device:type_name -> agntcy.identity.platform.v1alpha1.Device
	9, // 3: agntcy.identity.platform.v1alpha1.AuthService.AppInfo:input_type -> google.protobuf.Empty
	1, // 4: agntcy.identity.platform.v1alpha1.AuthService.Authorize:input_type -> agntcy.identity.platform.v1alpha1.AuthorizeRequest
	3, // 5: agntcy.identity.platform.v1alpha1.AuthService.Token:input_type -> agntcy.identity.platform.v1alpha1.TokenRequest
	9, // 6: agntcy.identity.platform.v1alpha1.AuthService.ExtAuthz:input_type -> google.protobuf.Empty
	5, // 7: agntcy.identity.platform.v1alpha1.AuthService.RegisterDevice:input_type -> agntcy.identity.platform.v1alpha1.RegisterDeviceRequest
	0, // 8: agntcy.identity.platform.v1alpha1.AuthService.AppInfo:output_type -> agntcy.identity.platform.v1alpha1.AppInfoResponse
	2, // 9: agntcy.identity.platform.v1alpha1.AuthService.Authorize:output_type -> agntcy.identity.platform.v1alpha1.AuthorizeResponse
	4, // 10: agntcy.identity.platform.v1alpha1.AuthService.Token:output_type -> agntcy.identity.platform.v1alpha1.TokenResponse
	9, // 11: agntcy.identity.platform.v1alpha1.AuthService.ExtAuthz:output_type -> google.protobuf.Empty
	9, // 12: agntcy.identity.platform.v1alpha1.AuthService.RegisterDevice:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agntcy_identity_platform_v1alpha1_auth_service_proto_init() }
func file_agntcy_identity_platform_v1alpha1_auth_service_proto_init() {
	if File_agntcy_identity_platform_v1alpha1_auth_service_proto != nil {
		return
	}
	file_agntcy_identity_platform_v1alpha1_app_proto_init()
	file_agntcy_identity_platform_v1alpha1_auth_proto_init()
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agntcy_identity_platform_v1alpha1_auth_service_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_platform_v1alpha1_auth_service_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_platform_v1alpha1_auth_service_proto_msgTypes,
	}.Build()
	File_agntcy_identity_platform_v1alpha1_auth_service_proto = out.File
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_goTypes = nil
	file_agntcy_identity_platform_v1alpha1_auth_service_proto_depIdxs = nil
}
