// Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// This file was autogenerated by go-to-protobuf. Do not edit it manually!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/platform/v1alpha1/device.proto

package identity_platform_sdk_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Devices used for user approval
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier for the Device.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// User ID associated with the Device.
	UserId *string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	// Subscription Token for the Device.
	SubscriptionToken *string `protobuf:"bytes,3,opt,name=subscription_token,json=subscriptionToken,proto3,oneof" json:"subscription_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_agntcy_identity_platform_v1alpha1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Device) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Device) GetSubscriptionToken() string {
	if x != nil && x.SubscriptionToken != nil {
		return *x.SubscriptionToken
	}
	return ""
}

var File_agntcy_identity_platform_v1alpha1_device_proto protoreflect.FileDescriptor

const file_agntcy_identity_platform_v1alpha1_device_proto_rawDesc = "" +
	"\n" +
	".agntcy/identity/platform/v1alpha1/device.proto\x12!agntcy.identity.platform.v1alpha1\"\x99\x01\n" +
	"\x06Device\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x01R\x06userId\x88\x01\x01\x122\n" +
	"\x12subscription_token\x18\x03 \x01(\tH\x02R\x11subscriptionToken\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_user_idB\x15\n" +
	"\x13_subscription_tokenBkZigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_gob\x06proto3"

var (
	file_agntcy_identity_platform_v1alpha1_device_proto_rawDescOnce sync.Once
	file_agntcy_identity_platform_v1alpha1_device_proto_rawDescData []byte
)

func file_agntcy_identity_platform_v1alpha1_device_proto_rawDescGZIP() []byte {
	file_agntcy_identity_platform_v1alpha1_device_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_platform_v1alpha1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_device_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_device_proto_rawDesc)))
	})
	return file_agntcy_identity_platform_v1alpha1_device_proto_rawDescData
}

var file_agntcy_identity_platform_v1alpha1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agntcy_identity_platform_v1alpha1_device_proto_goTypes = []any{
	(*Device)(nil), // 0: agntcy.identity.platform.v1alpha1.Device
}
var file_agntcy_identity_platform_v1alpha1_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agntcy_identity_platform_v1alpha1_device_proto_init() }
func file_agntcy_identity_platform_v1alpha1_device_proto_init() {
	if File_agntcy_identity_platform_v1alpha1_device_proto != nil {
		return
	}
	file_agntcy_identity_platform_v1alpha1_device_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_device_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_identity_platform_v1alpha1_device_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_platform_v1alpha1_device_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_platform_v1alpha1_device_proto_msgTypes,
	}.Build()
	File_agntcy_identity_platform_v1alpha1_device_proto = out.File
	file_agntcy_identity_platform_v1alpha1_device_proto_goTypes = nil
	file_agntcy_identity_platform_v1alpha1_device_proto_depIdxs = nil
}
