// Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agntcy/identity/platform/v1alpha1/policy_service.proto

package identity_platform_sdk_go

import (
	v1alpha1 "github.com/agntcy/identity-platform/api/server/agntcy/identity/platform/shared/v1alpha1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of Policies.
	Policies []*Policy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	// Pagination response.
	Pagination    *v1alpha1.PagedResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *ListPoliciesResponse) GetPagination() *v1alpha1.PagedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current page of the pagination
	Page *int32 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// The page size of the pagination
	Size *int32 `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	// The search query
	Query         *string `protobuf:"bytes,3,opt,name=query,proto3,oneof" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPoliciesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListPoliciesRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ListPoliciesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

type CreatePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human-readable name for the Policy.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description for the Policy.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The requester application that this policy applies to.
	AssignedTo    string `protobuf:"bytes,3,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePolicyRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

type GetPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy Id to get.
	PolicyId      string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UpdatePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy Id to update.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Policy parameters to update.
	Policy        *Policy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdatePolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type DeletePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy Id to delete.
	PolicyId      string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type ListRulesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of Rules.
	Rules []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	// Pagination response.
	Pagination    *v1alpha1.PagedResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListRulesResponse) GetPagination() *v1alpha1.PagedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Policy Id to which these Rules belong.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// The current page of the pagination
	Page *int32 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// The page size of the pagination
	Size *int32 `protobuf:"varint,3,opt,name=size,proto3,oneof" json:"size,omitempty"`
	// The search query
	Query         *string `protobuf:"bytes,4,opt,name=query,proto3,oneof" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListRulesRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ListRulesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListRulesRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ListRulesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

type CreateRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Policy Id to which these Rules belong.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// A human-readable name for the Rule.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description for the Rule.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The tasks that this Rule applies to.
	Tasks []string `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Need User Approval for this Rule.
	NeedsApproval *bool `protobuf:"varint,5,opt,name=needs_approval,json=needsApproval,proto3,oneof" json:"needs_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRuleRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRuleRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *CreateRuleRequest) GetNeedsApproval() bool {
	if x != nil && x.NeedsApproval != nil {
		return *x.NeedsApproval
	}
	return false
}

type GetRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Policy Id to which these Rules belong.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Rule Id to get.
	RuleId        string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetRuleRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *GetRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type UpdateRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Policy Id to which these Rules belong.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Rule Id to update.
	RuleId string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// Rule parameters to update.
	Rule          *Rule `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRuleRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdateRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *UpdateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Policy Id to which these Rules belong.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Rule Id to delete.
	RuleId        string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRuleRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DeleteRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

var File_agntcy_identity_platform_v1alpha1_policy_service_proto protoreflect.FileDescriptor

const file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDesc = "" +
	"\n" +
	"6agntcy/identity/platform/v1alpha1/policy_service.proto\x12!agntcy.identity.platform.v1alpha1\x1a9agntcy/identity/platform/shared/v1alpha1/pagination.proto\x1a.agntcy/identity/platform/v1alpha1/policy.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xca\x01\n" +
	"\x14ListPoliciesResponse\x12E\n" +
	"\bpolicies\x18\x01 \x03(\v2).agntcy.identity.platform.v1alpha1.PolicyR\bpolicies\x12\\\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v27.agntcy.identity.platform.shared.v1alpha1.PagedResponseH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"~\n" +
	"\x13ListPoliciesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x05H\x01R\x04size\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x03 \x01(\tH\x02R\x05query\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06_query\"\x81\x01\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vassigned_to\x18\x03 \x01(\tR\n" +
	"assignedToB\x0e\n" +
	"\f_description\"/\n" +
	"\x10GetPolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"u\n" +
	"\x13UpdatePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12A\n" +
	"\x06policy\x18\x02 \x01(\v2).agntcy.identity.platform.v1alpha1.PolicyR\x06policy\"2\n" +
	"\x13DeletePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"\xbf\x01\n" +
	"\x11ListRulesResponse\x12=\n" +
	"\x05rules\x18\x01 \x03(\v2'.agntcy.identity.platform.v1alpha1.RuleR\x05rules\x12\\\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v27.agntcy.identity.platform.shared.v1alpha1.PagedResponseH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"\x98\x01\n" +
	"\x10ListRulesRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x03 \x01(\x05H\x01R\x04size\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x04 \x01(\tH\x02R\x05query\x88\x01\x01B\a\n" +
	"\x05_pageB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06_query\"\xd0\x01\n" +
	"\x11CreateRuleRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05tasks\x18\x04 \x03(\tR\x05tasks\x12*\n" +
	"\x0eneeds_approval\x18\x05 \x01(\bH\x01R\rneedsApproval\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_needs_approval\"F\n" +
	"\x0eGetRuleRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\"\x86\x01\n" +
	"\x11UpdateRuleRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12;\n" +
	"\x04rule\x18\x03 \x01(\v2'.agntcy.identity.platform.v1alpha1.RuleR\x04rule\"I\n" +
	"\x11DeleteRuleRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId2\xe1\x0e\n" +
	"\rPolicyService\x12\xbb\x01\n" +
	"\fListPolicies\x126.agntcy.identity.platform.v1alpha1.ListPoliciesRequest\x1a7.agntcy.identity.platform.v1alpha1.ListPoliciesResponse\":\x92A\x1d\x12\rList Policies*\fListPolicies\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/policies\x12\xb3\x01\n" +
	"\tGetPolicy\x123.agntcy.identity.platform.v1alpha1.GetPolicyRequest\x1a).agntcy.identity.platform.v1alpha1.Policy\"F\x92A\x1d\x12\x10Get Policy by Id*\tGetPolicy\x82\xd3\xe4\x93\x02 \x12\x1e/v1alpha1/policies/{policy_id}\x12\xb0\x01\n" +
	"\fCreatePolicy\x126.agntcy.identity.platform.v1alpha1.CreatePolicyRequest\x1a).agntcy.identity.platform.v1alpha1.Policy\"=\x92A\x1d\x12\rCreate Policy*\fCreatePolicy\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1alpha1/policies\x12\xc1\x01\n" +
	"\fUpdatePolicy\x126.agntcy.identity.platform.v1alpha1.UpdatePolicyRequest\x1a).agntcy.identity.platform.v1alpha1.Policy\"N\x92A\x1d\x12\rUpdate Policy*\fUpdatePolicy\x82\xd3\xe4\x93\x02(:\x06policy2\x1e/v1alpha1/policies/{policy_id}\x12\xa6\x01\n" +
	"\fDeletePolicy\x126.agntcy.identity.platform.v1alpha1.DeletePolicyRequest\x1a\x16.google.protobuf.Empty\"F\x92A\x1d\x12\rDelete Policy*\fDeletePolicy\x82\xd3\xe4\x93\x02 *\x1e/v1alpha1/policies/{policy_id}\x12\xbe\x01\n" +
	"\tListRules\x123.agntcy.identity.platform.v1alpha1.ListRulesRequest\x1a4.agntcy.identity.platform.v1alpha1.ListRulesResponse\"F\x92A\x17\x12\n" +
	"List Rules*\tListRules\x82\xd3\xe4\x93\x02&\x12$/v1alpha1/policies/{policy_id}/rules\x12\xb9\x01\n" +
	"\aGetRule\x121.agntcy.identity.platform.v1alpha1.GetRuleRequest\x1a'.agntcy.identity.platform.v1alpha1.Rule\"R\x92A\x19\x12\x0eGet Rule by Id*\aGetRule\x82\xd3\xe4\x93\x020\x12./v1alpha1/policies/{policy_id}/rules/{rule_id}\x12\xb8\x01\n" +
	"\n" +
	"CreateRule\x124.agntcy.identity.platform.v1alpha1.CreateRuleRequest\x1a'.agntcy.identity.platform.v1alpha1.Rule\"K\x92A\x19\x12\vCreate Rule*\n" +
	"CreateRule\x82\xd3\xe4\x93\x02):\x01*\"$/v1alpha1/policies/{policy_id}/rules\x12\xc5\x01\n" +
	"\n" +
	"UpdateRule\x124.agntcy.identity.platform.v1alpha1.UpdateRuleRequest\x1a'.agntcy.identity.platform.v1alpha1.Rule\"X\x92A\x19\x12\vUpdate Rule*\n" +
	"UpdateRule\x82\xd3\xe4\x93\x026:\x04rule2./v1alpha1/policies/{policy_id}/rules/{rule_id}\x12\xae\x01\n" +
	"\n" +
	"DeleteRule\x124.agntcy.identity.platform.v1alpha1.DeleteRuleRequest\x1a\x16.google.protobuf.Empty\"R\x92A\x19\x12\vDelete Rule*\n" +
	"DeleteRule\x82\xd3\xe4\x93\x020*./v1alpha1/policies/{policy_id}/rules/{rule_id}\x1a\v\x92A\b\n" +
	"\x06PolicyBkZigithub.com/agntcy/identity-platform/api/server/agntcy/identity/platform/v1alpha1;identity_platform_sdk_gob\x06proto3"

var (
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescOnce sync.Once
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescData []byte
)

func file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescGZIP() []byte {
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescOnce.Do(func() {
		file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDesc)))
	})
	return file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDescData
}

var file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agntcy_identity_platform_v1alpha1_policy_service_proto_goTypes = []any{
	(*ListPoliciesResponse)(nil),   // 0: agntcy.identity.platform.v1alpha1.ListPoliciesResponse
	(*ListPoliciesRequest)(nil),    // 1: agntcy.identity.platform.v1alpha1.ListPoliciesRequest
	(*CreatePolicyRequest)(nil),    // 2: agntcy.identity.platform.v1alpha1.CreatePolicyRequest
	(*GetPolicyRequest)(nil),       // 3: agntcy.identity.platform.v1alpha1.GetPolicyRequest
	(*UpdatePolicyRequest)(nil),    // 4: agntcy.identity.platform.v1alpha1.UpdatePolicyRequest
	(*DeletePolicyRequest)(nil),    // 5: agntcy.identity.platform.v1alpha1.DeletePolicyRequest
	(*ListRulesResponse)(nil),      // 6: agntcy.identity.platform.v1alpha1.ListRulesResponse
	(*ListRulesRequest)(nil),       // 7: agntcy.identity.platform.v1alpha1.ListRulesRequest
	(*CreateRuleRequest)(nil),      // 8: agntcy.identity.platform.v1alpha1.CreateRuleRequest
	(*GetRuleRequest)(nil),         // 9: agntcy.identity.platform.v1alpha1.GetRuleRequest
	(*UpdateRuleRequest)(nil),      // 10: agntcy.identity.platform.v1alpha1.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),      // 11: agntcy.identity.platform.v1alpha1.DeleteRuleRequest
	(*Policy)(nil),                 // 12: agntcy.identity.platform.v1alpha1.Policy
	(*v1alpha1.PagedResponse)(nil), // 13: agntcy.identity.platform.shared.v1alpha1.PagedResponse
	(*Rule)(nil),                   // 14: agntcy.identity.platform.v1alpha1.Rule
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_agntcy_identity_platform_v1alpha1_policy_service_proto_depIdxs = []int32{
	12, // 0: agntcy.identity.platform.v1alpha1.ListPoliciesResponse.policies:type_name -> agntcy.identity.platform.v1alpha1.Policy
	13, // 1: agntcy.identity.platform.v1alpha1.ListPoliciesResponse.pagination:type_name -> agntcy.identity.platform.shared.v1alpha1.PagedResponse
	12, // 2: agntcy.identity.platform.v1alpha1.UpdatePolicyRequest.policy:type_name -> agntcy.identity.platform.v1alpha1.Policy
	14, // 3: agntcy.identity.platform.v1alpha1.ListRulesResponse.rules:type_name -> agntcy.identity.platform.v1alpha1.Rule
	13, // 4: agntcy.identity.platform.v1alpha1.ListRulesResponse.pagination:type_name -> agntcy.identity.platform.shared.v1alpha1.PagedResponse
	14, // 5: agntcy.identity.platform.v1alpha1.UpdateRuleRequest.rule:type_name -> agntcy.identity.platform.v1alpha1.Rule
	1,  // 6: agntcy.identity.platform.v1alpha1.PolicyService.ListPolicies:input_type -> agntcy.identity.platform.v1alpha1.ListPoliciesRequest
	3,  // 7: agntcy.identity.platform.v1alpha1.PolicyService.GetPolicy:input_type -> agntcy.identity.platform.v1alpha1.GetPolicyRequest
	2,  // 8: agntcy.identity.platform.v1alpha1.PolicyService.CreatePolicy:input_type -> agntcy.identity.platform.v1alpha1.CreatePolicyRequest
	4,  // 9: agntcy.identity.platform.v1alpha1.PolicyService.UpdatePolicy:input_type -> agntcy.identity.platform.v1alpha1.UpdatePolicyRequest
	5,  // 10: agntcy.identity.platform.v1alpha1.PolicyService.DeletePolicy:input_type -> agntcy.identity.platform.v1alpha1.DeletePolicyRequest
	7,  // 11: agntcy.identity.platform.v1alpha1.PolicyService.ListRules:input_type -> agntcy.identity.platform.v1alpha1.ListRulesRequest
	9,  // 12: agntcy.identity.platform.v1alpha1.PolicyService.GetRule:input_type -> agntcy.identity.platform.v1alpha1.GetRuleRequest
	8,  // 13: agntcy.identity.platform.v1alpha1.PolicyService.CreateRule:input_type -> agntcy.identity.platform.v1alpha1.CreateRuleRequest
	10, // 14: agntcy.identity.platform.v1alpha1.PolicyService.UpdateRule:input_type -> agntcy.identity.platform.v1alpha1.UpdateRuleRequest
	11, // 15: agntcy.identity.platform.v1alpha1.PolicyService.DeleteRule:input_type -> agntcy.identity.platform.v1alpha1.DeleteRuleRequest
	0,  // 16: agntcy.identity.platform.v1alpha1.PolicyService.ListPolicies:output_type -> agntcy.identity.platform.v1alpha1.ListPoliciesResponse
	12, // 17: agntcy.identity.platform.v1alpha1.PolicyService.GetPolicy:output_type -> agntcy.identity.platform.v1alpha1.Policy
	12, // 18: agntcy.identity.platform.v1alpha1.PolicyService.CreatePolicy:output_type -> agntcy.identity.platform.v1alpha1.Policy
	12, // 19: agntcy.identity.platform.v1alpha1.PolicyService.UpdatePolicy:output_type -> agntcy.identity.platform.v1alpha1.Policy
	15, // 20: agntcy.identity.platform.v1alpha1.PolicyService.DeletePolicy:output_type -> google.protobuf.Empty
	6,  // 21: agntcy.identity.platform.v1alpha1.PolicyService.ListRules:output_type -> agntcy.identity.platform.v1alpha1.ListRulesResponse
	14, // 22: agntcy.identity.platform.v1alpha1.PolicyService.GetRule:output_type -> agntcy.identity.platform.v1alpha1.Rule
	14, // 23: agntcy.identity.platform.v1alpha1.PolicyService.CreateRule:output_type -> agntcy.identity.platform.v1alpha1.Rule
	14, // 24: agntcy.identity.platform.v1alpha1.PolicyService.UpdateRule:output_type -> agntcy.identity.platform.v1alpha1.Rule
	15, // 25: agntcy.identity.platform.v1alpha1.PolicyService.DeleteRule:output_type -> google.protobuf.Empty
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agntcy_identity_platform_v1alpha1_policy_service_proto_init() }
func file_agntcy_identity_platform_v1alpha1_policy_service_proto_init() {
	if File_agntcy_identity_platform_v1alpha1_policy_service_proto != nil {
		return
	}
	file_agntcy_identity_platform_v1alpha1_policy_proto_init()
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDesc), len(file_agntcy_identity_platform_v1alpha1_policy_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agntcy_identity_platform_v1alpha1_policy_service_proto_goTypes,
		DependencyIndexes: file_agntcy_identity_platform_v1alpha1_policy_service_proto_depIdxs,
		MessageInfos:      file_agntcy_identity_platform_v1alpha1_policy_service_proto_msgTypes,
	}.Build()
	File_agntcy_identity_platform_v1alpha1_policy_service_proto = out.File
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_goTypes = nil
	file_agntcy_identity_platform_v1alpha1_policy_service_proto_depIdxs = nil
}
