# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Corona & Blackduck Scan

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["PYRA-280-enable-blackduck-scan-on-pyramid-platform"] 

permissions: read-all

jobs:
  security-scan:
    name: Run Security Scans
    uses: cisco-eti/gh-reusable-workflows/.github/workflows/corona-blackduck-scan.yaml@production
    permissions:
      contents: read
      pull-requests: write
    with:
      runner-group: SRE-Large-Runners
      continue-on-error: false
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      enable-corona: true
      enable-blackduck: true
      language: "go"
      image-name: ${{ github.event.repository.name }}
      image-tag: "pr-${{ github.event.pull_request.number }}"
      corona-product-name: "Pyramid Platform"
      # Add your specific values for these parameters or remove if not needed
      # corona-product-id: ""
      # corona-release-id: ""
      # corona-csdl-id: ""
      # corona-security-contact: ""
      # corona-engineering-contact: ""
      # corona-image-admins: ""
      bd-scanning-directory: "."
      ghcr-org-registry: "ghcr.io/cisco-eti"
    secrets:
      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      ghcr-username: ${{ secrets.GHCR_USERNAME }}
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
      ghcr-org-username: ${{ secrets.GHCR_ORG_USERNAME }}
      ghcr-org-token: ${{ secrets.GHCR_ORG_TOKEN }}