# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: dependency

on:
  # Review dependencies on pull requests to the default branch
  pull_request:
    branches: ["main"]

# Declare default permissions as read-only
permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.1.7
      - name: 🔂 dependency review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
        with:
          fail-on-severity: "high"
          deny-licenses: "AGPL-1.0, AGPL-3.0"
          comment-summary-in-pr: true
          warn-on-openssf-scorecard-level: 3
