# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
name: Run all tests

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: read
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: test
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running all tests..."
          ./deployments/test/unit-test.sh
