# Copyright 2025 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

---
name: Run all tests

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: test
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running all tests..."
          ./deployments/test/unit-test.sh
