# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: sonarqube scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  ################################## SonarQube  Scan ##############################
  #################################################################################
  sonar-go-tests-and-scan:
    name: Go tests + SonarQube scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run Go tests with coverage
        working-directory: backend
        run: |
          go test ./... -covermode=atomic -coverprofile=coverage.out

      - name: Normalize Go coverage paths (module -> repo paths)
        working-directory: backend
        run: |
          MODULE_PATH=$(go list -m)
          echo "Detected Go module: ${MODULE_PATH}"
          sed -i "s#${MODULE_PATH}/#backend/#g" coverage.out

      - name: Prepare frontend env for Yarn
        working-directory: frontend
        run: |
          # Ensure .env exists because Yarn injects env from .env via .yarnrc.yml
          if [ ! -f .env ]; then
            if [ -f .env.sample ]; then
              cp .env.sample .env
            else
              touch .env
            fi
          fi
          if grep -q '^ARTIFACTORY_PASSWORD=' .env; then
            sed -i "s#^ARTIFACTORY_PASSWORD=.*#ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }}#" .env
          else
            echo 'ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }}' >> .env
          fi

      - name: Set up Node (for frontend tests)
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install frontend dependencies
        working-directory: frontend
        env:
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          corepack enable
          yarn install --frozen-lockfile || yarn install

      - name: Run frontend tests with coverage (Vitest)
        working-directory: frontend
        run: |
          yarn test:coverage

      - name: Import Vault Secret
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ vars.KEEPER_URL }}
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            ${{ vars.VAULT_SECRET_PATH }}  SONAR_CLOUD_URL   | SONAR_URL ;
            ${{ vars.VAULT_SECRET_PATH }}  SONAR_CLOUD_TOKEN | SONAR_TOKEN

      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_URL }}
        with:
          args: >-
            -Dproject.settings=.github/linters/sonar-project.properties
            # -Dsonar.qualitygate.wait=true
